[package]
name = "leuchtkraft"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3"
pest = "2"
pest_derive = "2"
colored = "2"
log = "0.4"
env_logger = "0.9"
